[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "raceindycar"
version = "1.0"
description = "IndyCar data access, similar to FastF1"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Parker Merritt", email = "parkermerritt05@gmail.com" },
]
dependencies = [
    "pandas",
    "requests",
    "requests-cache",
    "pdfplumber",
    "matplotlib",
]
classifiers = ["Programming Language :: Python :: 3",
            "Operating System :: OS Independent"]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/parkermerritt05/raceindycar"
Repository = "https://github.com/parkermerritt05/raceindycar"
Issues = "https://github.com/parkermerritt05/raceindycar/issues"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
